# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sek.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import threading
import time

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 591)
        MainWindow.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(30, 340, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: 1px solid white;\n"
"}")
        self.start_button.setObjectName("start_button")
        self.finish_button = QtWidgets.QPushButton(self.centralwidget)
        self.finish_button.setGeometry(QtCore.QRect(290, 340, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.finish_button.setFont(font)
        self.finish_button.setStyleSheet("QPushButton{\n"
"    color:white;\n"
"    border: 1px solid white;\n"
"}\n"
"")
        self.finish_button.setObjectName("finish_button")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 450, 471, 101))
        font = QtGui.QFont()
        font.setPointSize(42)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 20, 471, 291))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.textEdit.setFont(font)
        self.textEdit.setStatusTip("")
        self.textEdit.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.add_func()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "Старт"))
        self.finish_button.setText(_translate("MainWindow", "Сброс"))
        self.lineEdit.setText(_translate("MainWindow", "00:00:00"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", "ВВЕДИТЕ ТЕКСТ "))
    isStart = False
    def add_func(self):
        self.start_button.clicked.connect(self.start)
        self.finish_button.clicked.connect(self.finish)

    def start(self):
        global isStart
        isStart = True
        thr = threading.Thread(target=self.timere, name='thr-1')
        thr.start()

    def finish(self):
        global count
        global isStart
        isStart = False
        print(isStart)
        text = self.textEdit.toPlainText()
        minn = count / 60
        print(minn)
        self.textEdit.close()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Label.setGeometry(30, 130, 491, 111)
        self.Label.setFont(font)
        self.Label.setObjectName('Label')
        self.Label.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.Label.setAlignment(Qt.AlignCenter)
        self.Label.setText('Скорость вашей печати: ' + str(len(text)//minn) + ' символов в минуту')
        print('Скорость вашей печати: ' + str(len(text)//minn) + ' символов в минуту')

    def timere(self):
        global count
        global isStart
        sec = 0
        while isStart:
            time.sleep(1)
            sec += 1
            hours = sec // 3600
            minut = (sec % 3600) // 60
            seconds = sec % 60
            if hours > 99:
                isStart == False
            else:
                hours = str(hours)
                minut = str(minut)
                seconds = str(seconds)
                time_str = '0' * (2 - len(hours)) + hours + ':' + '0' * (2 - len(minut)) + minut + ':' + '0' * (
                            2 - len(seconds)) + seconds
                self.lineEdit.setText(time_str)
            count = sec
        else:
            return

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
